import { easeOutBack, easeOutBounce, easeOutCubic, easeOutElastic, linear, step } from './easing'
import type { Preset } from './types'

const DARK = '#1a1a1a'

/**
 * 30 presets across 6 categories, built from one shared primitive engine (split unit,
 * opacity/x/y/scale/rotate/fill/glow, stagger order, easing, optional oscillation/
 * colorFlicker/decoration) — not 30 separate animation implementations. See DEC-003 and
 * DEC-006 for the model and for which named effects (blur, true clip-masks, gradients,
 * particles, 3D flip) are approximated rather than pixel-faithful in this V1 engine.
 */
export const PRESETS: Preset[] = [
  // ---- Clean ----
  {
    id: 'fade',
    name: 'Fade',
    category: 'Clean',
    split: 'block',
    entranceMs: 700,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
  {
    id: 'rise',
    name: 'Rise',
    category: 'Clean',
    split: 'block',
    entranceMs: 850,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, y: 28 },
    to: { opacity: 1, y: 0 },
  },
  {
    id: 'slide',
    name: 'Slide',
    category: 'Clean',
    split: 'block',
    entranceMs: 700,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, x: -50 },
    to: { opacity: 1, x: 0 },
  },
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'Clean',
    split: 'block',
    entranceMs: 650,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, scale: 0.82 },
    to: { opacity: 1, scale: 1 },
  },
  {
    id: 'focus',
    name: 'Focus',
    category: 'Clean',
    // Approximation: canvas text objects don't expose an easy per-object blur filter,
    // so "coming into focus" is simulated with a soft scale settle instead of true blur.
    split: 'block',
    entranceMs: 750,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, scale: 1.1 },
    to: { opacity: 1, scale: 1 },
  },

  // ---- Typing ----
  {
    id: 'typewriter',
    name: 'Typewriter',
    category: 'Typing',
    split: 'character',
    entranceMs: 60,
    holdMs: 1200,
    ease: step,
    from: { opacity: 0 },
    to: { opacity: 1 },
    stagger: { order: 'forward', amountMs: 900 },
  },
  {
    id: 'word-by-word',
    name: 'Word by Word',
    category: 'Typing',
    split: 'word',
    entranceMs: 260,
    holdMs: 1100,
    ease: easeOutCubic,
    from: { opacity: 0, y: 10 },
    to: { opacity: 1, y: 0 },
    stagger: { order: 'forward', amountMs: 700 },
  },
  {
    id: 'cascade',
    name: 'Cascade',
    category: 'Typing',
    split: 'character',
    entranceMs: 420,
    holdMs: 1100,
    ease: easeOutCubic,
    from: { opacity: 0, y: 14 },
    to: { opacity: 1, y: 0 },
    stagger: { order: 'forward', amountMs: 650 },
  },
  {
    id: 'decode',
    name: 'Decode',
    category: 'Typing',
    // Approximation of a scramble-to-real-text decode using a color flicker + settle,
    // rather than swapping through random glyphs.
    split: 'character',
    entranceMs: 260,
    holdMs: 1100,
    ease: linear,
    from: { opacity: 0.4, fill: '#2b6cff' },
    to: { opacity: 1, fill: DARK },
    stagger: { order: 'random', amountMs: 500 },
    colorFlicker: true,
  },
  {
    id: 'tracking',
    name: 'Tracking',
    category: 'Typing',
    // Approximation of letter-spacing collapse via block scaleX-like settle (uniform
    // scale, since per-axis scale isn't wired through the shared primitive set yet).
    split: 'block',
    entranceMs: 700,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, scale: 1.3 },
    to: { opacity: 1, scale: 1 },
  },

  // ---- Editorial ----
  {
    id: 'mask-reveal',
    name: 'Mask Reveal',
    category: 'Editorial',
    // Approximation of a clip-path wipe using scale + opacity (no true clip mask yet).
    split: 'block',
    entranceMs: 650,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, scale: 0.94 },
    to: { opacity: 1, scale: 1 },
  },
  {
    id: 'highlight',
    name: 'Highlight',
    category: 'Editorial',
    split: 'block',
    entranceMs: 500,
    holdMs: 1300,
    ease: easeOutCubic,
    from: { opacity: 0, fill: '#ffb800', scale: 1.04 },
    to: { opacity: 1, fill: DARK, scale: 1 },
  },
  {
    id: 'underline',
    name: 'Underline',
    category: 'Editorial',
    split: 'block',
    entranceMs: 650,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0 },
    to: { opacity: 1 },
    decoration: 'underline',
  },
  {
    id: 'split-reveal',
    name: 'Split Reveal',
    category: 'Editorial',
    // Approximation: two halves converging is simplified to a center-out scale settle.
    split: 'block',
    entranceMs: 600,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, scale: 1.5 },
    to: { opacity: 1, scale: 1 },
  },
  {
    id: 'stamp',
    name: 'Stamp',
    category: 'Editorial',
    split: 'block',
    entranceMs: 380,
    holdMs: 1300,
    ease: easeOutBack,
    from: { opacity: 0, scale: 1.6 },
    to: { opacity: 1, scale: 1 },
  },

  // ---- Playful ----
  {
    id: 'pop',
    name: 'Pop',
    category: 'Playful',
    split: 'word',
    entranceMs: 420,
    holdMs: 1200,
    ease: easeOutBack,
    from: { opacity: 0, scale: 0.5 },
    to: { opacity: 1, scale: 1 },
    stagger: { order: 'forward', amountMs: 300 },
  },
  {
    id: 'bounce',
    name: 'Bounce',
    category: 'Playful',
    split: 'character',
    entranceMs: 600,
    holdMs: 1100,
    ease: easeOutBounce,
    from: { opacity: 0, y: -26 },
    to: { opacity: 1, y: 0 },
    stagger: { order: 'forward', amountMs: 500 },
  },
  {
    id: 'elastic',
    name: 'Elastic',
    category: 'Playful',
    split: 'word',
    entranceMs: 750,
    holdMs: 1100,
    ease: easeOutElastic,
    from: { opacity: 0, scale: 0.3 },
    to: { opacity: 1, scale: 1 },
    stagger: { order: 'forward', amountMs: 250 },
  },
  {
    id: 'wave',
    name: 'Wave',
    category: 'Playful',
    split: 'character',
    entranceMs: 550,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, y: 0 },
    to: { opacity: 1, y: 0 },
    stagger: { order: 'center-out', amountMs: 500 },
    oscillation: { channel: 'y', amplitude: 14, cycles: 1.5 },
  },
  {
    id: 'flip',
    name: 'Flip',
    category: 'Playful',
    // Approximation of a 3D Y-axis flip using 2D rotation (no perspective transform).
    split: 'character',
    entranceMs: 450,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, rotate: -85 },
    to: { opacity: 1, rotate: 0 },
    stagger: { order: 'forward', amountMs: 400 },
  },

  // ---- Bold ----
  {
    id: 'impact',
    name: 'Impact',
    category: 'Bold',
    split: 'block',
    entranceMs: 260,
    holdMs: 1400,
    ease: easeOutCubic,
    from: { opacity: 0, scale: 1.6 },
    to: { opacity: 1, scale: 1 },
  },
  {
    id: 'shake',
    name: 'Shake',
    category: 'Bold',
    split: 'block',
    entranceMs: 500,
    holdMs: 1300,
    ease: easeOutCubic,
    from: { opacity: 0 },
    to: { opacity: 1 },
    oscillation: { channel: 'x', amplitude: 10, cycles: 4 },
  },
  {
    id: 'glitch',
    name: 'Glitch',
    category: 'Bold',
    // Approximation: color-flicker + x jitter stands in for RGB-split/scanline glitch.
    split: 'character',
    entranceMs: 350,
    holdMs: 1200,
    ease: linear,
    from: { opacity: 0.3, fill: '#ff2fd0' },
    to: { opacity: 1, fill: DARK },
    stagger: { order: 'random', amountMs: 300 },
    oscillation: { channel: 'x', amplitude: 4, cycles: 6 },
    colorFlicker: true,
  },
  {
    id: 'smash',
    name: 'Smash',
    category: 'Bold',
    split: 'block',
    entranceMs: 300,
    holdMs: 1400,
    ease: easeOutBack,
    from: { opacity: 0, scale: 2.2 },
    to: { opacity: 1, scale: 1 },
  },
  {
    id: 'countdown',
    name: 'Countdown',
    category: 'Bold',
    split: 'block',
    delayMs: 350,
    entranceMs: 260,
    holdMs: 1300,
    ease: easeOutBack,
    from: { opacity: 0, scale: 1.3 },
    to: { opacity: 1, scale: 1 },
  },

  // ---- Light & Color ----
  {
    id: 'neon',
    name: 'Neon',
    category: 'Light & Color',
    split: 'block',
    entranceMs: 650,
    holdMs: 1300,
    ease: easeOutCubic,
    from: { opacity: 0, fill: '#ff45d7', glowColor: '#ff45d7', glowBlur: 0 },
    to: { opacity: 1, fill: '#ffffff', glowColor: '#ff45d7', glowBlur: 18 },
  },
  {
    id: 'glow-pulse',
    name: 'Glow Pulse',
    category: 'Light & Color',
    split: 'block',
    entranceMs: 700,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, glowColor: '#2b6cff', glowBlur: 2 },
    to: { opacity: 1, glowColor: '#2b6cff', glowBlur: 14 },
    oscillation: { channel: 'glowBlur', amplitude: 5, cycles: 2 },
  },
  {
    id: 'shine',
    name: 'Shine',
    category: 'Light & Color',
    // Approximation: a sweeping specular highlight is simplified to a brief flash.
    split: 'block',
    entranceMs: 500,
    holdMs: 1300,
    ease: easeOutCubic,
    from: { opacity: 0, fill: '#ffffff', scale: 0.97 },
    to: { opacity: 1, fill: DARK, scale: 1 },
  },
  {
    id: 'gradient',
    name: 'Gradient',
    category: 'Light & Color',
    // Approximation: a moving multi-stop gradient is simplified to a two-color sweep.
    split: 'block',
    entranceMs: 750,
    holdMs: 1200,
    ease: linear,
    from: { opacity: 0, fill: '#2b6cff' },
    to: { opacity: 1, fill: '#ff45d7' },
  },
  {
    id: 'sparkle',
    name: 'Sparkle',
    category: 'Light & Color',
    split: 'character',
    entranceMs: 350,
    holdMs: 1200,
    ease: easeOutCubic,
    from: { opacity: 0, glowColor: '#ffd23f', glowBlur: 0, scale: 0.8 },
    to: { opacity: 1, glowColor: '#ffd23f', glowBlur: 10, scale: 1 },
    stagger: { order: 'random', amountMs: 550 },
  },
]

export const DEFAULT_PRESET_IDS = ['fade', 'rise', 'typewriter', 'highlight', 'pop']
